"""Initial schema - stores coupons bundles

Revision ID: d69c7a36b331
Revises: 
Create Date: 2026-03-18 01:52:39.515364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69c7a36b331'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=True)
    op.create_table('user_bundles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('week_label', sa.String(length=50), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('total_savings', sa.Float(), nullable=True),
    sa.Column('coupon_count', sa.Integer(), nullable=True),
    sa.Column('store_ids', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bundles_is_active'), 'user_bundles', ['is_active'], unique=False)
    op.create_table('coupon_bundles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('week_label', sa.String(length=50), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('total_savings', sa.Float(), nullable=True),
    sa.Column('coupon_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bundle_store_active', 'coupon_bundles', ['store_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_coupon_bundles_is_active'), 'coupon_bundles', ['is_active'], unique=False)
    op.create_index(op.f('ix_coupon_bundles_store_id'), 'coupon_bundles', ['store_id'], unique=False)
    op.create_index(op.f('ix_coupon_bundles_valid_until'), 'coupon_bundles', ['valid_until'], unique=False)
    op.create_table('coupons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount', sa.String(length=50), nullable=False),
    sa.Column('discount_value', sa.Float(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_coupon_expiry', 'coupons', ['expiry_date'], unique=False)
    op.create_index('idx_coupon_store_active', 'coupons', ['store_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_coupons_expiry_date'), 'coupons', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_coupons_is_active'), 'coupons', ['is_active'], unique=False)
    op.create_index(op.f('ix_coupons_store_id'), 'coupons', ['store_id'], unique=False)
    op.create_table('bundle_coupons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bundle_id', sa.String(length=36), nullable=False),
    sa.Column('coupon_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['coupon_bundles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bundle_coupon_unique', 'bundle_coupons', ['bundle_id', 'coupon_id'], unique=True)
    op.create_index(op.f('ix_bundle_coupons_bundle_id'), 'bundle_coupons', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_bundle_coupons_coupon_id'), 'bundle_coupons', ['coupon_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bundle_coupons_coupon_id'), table_name='bundle_coupons')
    op.drop_index(op.f('ix_bundle_coupons_bundle_id'), table_name='bundle_coupons')
    op.drop_index('idx_bundle_coupon_unique', table_name='bundle_coupons')
    op.drop_table('bundle_coupons')
    op.drop_index(op.f('ix_coupons_store_id'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_is_active'), table_name='coupons')
    op.drop_index(op.f('ix_coupons_expiry_date'), table_name='coupons')
    op.drop_index('idx_coupon_store_active', table_name='coupons')
    op.drop_index('idx_coupon_expiry', table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_coupon_bundles_valid_until'), table_name='coupon_bundles')
    op.drop_index(op.f('ix_coupon_bundles_store_id'), table_name='coupon_bundles')
    op.drop_index(op.f('ix_coupon_bundles_is_active'), table_name='coupon_bundles')
    op.drop_index('idx_bundle_store_active', table_name='coupon_bundles')
    op.drop_table('coupon_bundles')
    op.drop_index(op.f('ix_user_bundles_is_active'), table_name='user_bundles')
    op.drop_table('user_bundles')
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.drop_table('stores')
    # ### end Alembic commands ###
